### PR TITLE
added redirects for old dryad landing pages

### PR DESCRIPTION
**Pull request by briri**
Added redirects for the old dryad landing pages. All requests for `/resource/[:doc].[:version]/[:file].[:version]` will be redirected to the main dataset landing page. 

For example:
- Dataset: https://dryad-dev.cdlib.org/resource/doi:10.5061/dryad.kq201
- Version of Dataset: https://dryad-dev.cdlib.org/resource/doi:10.5061/dryad.kq201.2
- File within a Dataset: https://dryad-dev.cdlib.org/resource/doi:10.5061/dryad.kq201/3
- Version of File within a Dataset: https://dryad-dev.cdlib.org/resource/doi:10.5061/dryad.kq201/3.1
- File within a Version of a Dataset: https://dryad-dev.cdlib.org/resource/doi:10.5061/dryad.kq201.2/3
- Version of File within a Version of a Dataset: https://dryad-dev.cdlib.org/resource/doi:10.5061/dryad.kq201.2/3.1

Will all be redirected to: https://dryad-dev.cdlib.org/stash/dataset/doi:10.5061/dryad.kq201?latest=true

### CODE REVIEW

**Comment by sfisher** [comment]
It seems like Travis is still failing these tests.  :-/

**Review by sfisher — COMMENTED** [review]
Hey Brian.

I don't think you want the ?latest=true on those URLs probably.

The latest is mostly for curators who want to peek at datasets that haven't been published yet.  If you're a curator and the latest is true then it will show you the latest.  If you're a curator and go in without it then you see the public page.  I think it only creates the links that way from the curator dashboard.

It shouldn't make any difference for non-logged-in people since it has logic to only show published stuff to others, but it's not needed for URLs for anyone but curators and I think these redirect URLs are for the general public.

**Comment by briri** [comment]
ah ok @sfisher. I have removed that `latest=true` query param.

**Review by sfisher — APPROVED** [review]
Looks good to me, Brian.  Thanks for setting this up.

**Pull request merged**
