### PR TITLE
Added deploy for stage-2c

### PR DESCRIPTION
**Pull request by briri**
- Added capistrano deploy file for the new linux2 stage-2c instance.
- Removed old linux1 stage deploy

### CODE REVIEW

**Comment by ryscher** [comment]
Note that this server is already set as deploy `migration`. We don't want to accidentally deploy it with the wrong code.

**Review by sfisher — APPROVED** [review]
This looks OK, but I can't really see from this PR how we're dealing with all the deploy scripts since it's a narrow view.  I think originally I had stage (both servers), stage1 & stage2.  I think it's fine for all these to point to the new Linux2 servers as we get them going.

We definitely don't want to get rid of the migration deploy in there until we're done with it (and it is using the former second stage server from linux1).

**Comment by sfisher** [comment]
PS.  I'm also seeing some Travis failure here now.  Not sure if it's temporary or not.  :-/

**Comment by briri** [comment]
The following capistrano deploy targets are available after this PR:
Screen Shot 2019-07-23 at 11 03 19 AM

**Comment by briri** [comment]
created a corresponding branch in stash and tests are now passing 🙃

**Pull request merged**
