### PR TITLE
added new geoblacklight field to sample config

### PR DESCRIPTION
**Pull request by briri**
Additional work for (issue #283)[https://github.com/CDL-Dryad/dryad-product-roadmap/issues/283]

Adding new `dryad_related_publication_name` geoblacklight field to the sample config.

Added test for correct facet display

### CODE REVIEW

**Review by sfisher — APPROVED** [review]
Thanks Brian.  That looks good.

**Comment by briri** [comment]
oops. wait for the tests before merging!

**Comment by briri** [comment]
updates required corresponding changes to some of the files in stash repo. Will restart Travis tests once they are in place.

**Review by sfisher — APPROVED** [review]
I ran the tests locally against things and they passed.

Thanks for adding all the SOLR stuff to the tests.  This will also make it easier to troubleshoot the changes we need to make for SOLR on the real system since we have files that are correct to look at in addition to the documentation.

Travis seems to be fine with this also.  🤞

**Pull request merged**
