### PR TITLE
Response test -- Retain the original publication date

### PR DESCRIPTION
**Pull request by ryscher**
Add a response test for https://github.com/CDL-Dryad/stash/pull/173.

As a side effect, this does some basic testing that curation activities are created when submitted through the API.

### CODE REVIEW

**Comment by sfisher** [comment]
Hi @ryscher ,  I'm still seeing errors in one of the tests when it's run on travis.ci.

The error it gives is below.   It looks like one date is 2019-05-19 and the otehr is 2019-05-29 .. Any thoughts on what is going on?  It seems to work on my local machine.  Very weird.

```
1) StashApi::DatasetsController#create does not update the publication date if one is already set
     Failure/Error: expect(@resource.publication_date).to be_within(10.seconds).of(publish_date)
       expected 2019-05-29 21:06:27.000000000 +0000 to be within 10 of 2019-05-19 21:06:27 +0000
     # ./spec/responses/stash_api/datasets_controller_spec.rb:99:in `block (3 levels) in <module:StashApi>'
```

**Comment by ryscher** [comment]
That's what I would expect if the stash repo wasn't updated yet. I'll look at it...

**Comment by ryscher** [comment]
It looks like the original test failed due to a problem with Travis downloading a component. I re-ran the test and it passed.

**Comment by sfisher** [comment]
This looks good, @ryscher .   Thanks for hassling with getting travis to pass the tests.

**Pull request merged**
